version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: is-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - isnet
    restart: unless-stopped

  app:
    image: isapp:lab8
    container_name: is-app
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      ConnectionStrings__Mssql: "Server=mssql,1433;Database=${DB_NAME};User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True"
      App__Version: "${APP_VERSION}"
    depends_on:
      - mssql
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - isnet
    restart: unless-stopped

volumes:
  mssql_data:

networks:
  isnet:
    driver: bridge

